import ERROR_MESSAGES from './errors';

const AUTH_ERROR_MESSAGES = {
  INVALID_EMAIL: ERROR_MESSAGES.INVALID_EMAIL,
  INVALID_PASSWORD: ERROR_MESSAGES.INVALID_PASSWORD,
  INVALID_FIRST_NAME: ERROR_MESSAGES.INVALID_FIRST_NAME,
  INVALID_LAST_NAME: ERROR_MESSAGES.INVALID_LAST_NAME,
  INVALID_PHONE_NUMBER: ERROR_MESSAGES.INVALID_PHONE_NUMBER,
  INVALID_DATE_OF_BIRTH: ERROR_MESSAGES.INVALID_DATE_OF_BIRTH,
  DUPLICATE_USER_EMAIL: ERROR_MESSAGES.DUPLICATE_USER_EMAIL,
  DUPLICATE_USER_PHONE_NUMBER: ERROR_MESSAGES.DUPLICATE_USER_PHONE_NUMBER,
  INCORRECT_PASSWORD: ERROR_MESSAGES.INCORRECT_PASSWORD,
  EMAIL_NOT_FOUND: ERROR_MESSAGES.EMAIL_NOT_FOUND,
} as const;

export default AUTH_ERROR_MESSAGES;
